### ISSUE TITLE
 intermediate/tilt position 1 and 2 for iveo motors 

### ISSUE THREAD

**Issue by Deinjo** [Kannix2005/homeassistant-selve#10]
The support of the intermediate/tilt position 1 and 2 for iveo motors would be very helpful for common use. :-)

**Comment by Kannix2005** [comment]
Did you try that with the newest version? ;)

**Comment by Deinjo** [comment]
Just updated to 2.3.0. How do I configure it so that I can also approach the tilt position?
I continue to see only Up, Stop, Down in the Card. Shouldn't there now also be keys for the TiltPos ?

**Comment by Deinjo** [comment]
> Just updated to 2.3.0. How do I configure it so that I can also approach the tilt position? I continue to see only Up, Stop, Down in the Card. Shouldn't there now also be keys for the TiltPos ?

With v3.0.6-1 still the same
