### ISSUE TITLE
Random bug after reboot

### ISSUE THREAD

**Issue by chekdo** [Kannix2005/homeassistant-selve#12]
**Describe the bug**
When my Home assitant restart, the service selve doesn't work frequently. I nedd to restart again or to switch off (power off) the raspberry. 

**To Reproduce**
1. update a component (core for example)
2. After the restart, the selve integration doesn't work
3. I see many error

**Expected behavior**
No error and works directly after a reboot and or an update

**Screenshots**
![image](https://user-images.githubusercontent.com/101399672/217590202-5980f89c-9597-4494-b972-1c8f9ee7f3a7.png)

**Desktop (please complete the following information):**
 - Home Assistant 2023.2.3
 - Hassio
 - Used shutters (commeo) 

**Additional context**
In the file configuration.yaml, I configure the port by ID because the num of the port change sometimes 
 selve:
  port: /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01F5V1-if00-port0

**Comment by Kannix2005** [comment]
Hey @chekdo,
Please try to set up the integration via the integration setup flow (settings -> integrations -> +-button). The configuration via configuration.yaml is deprecated and unreliable.

Best

**Comment by chekdo** [comment]
I do what you recommended to me and I see that I have two integration installed. (gpulido and Kannix2005). I delete the first one, and erase the line in configuration.yaml.
It seems to be better. thanks a lot.
