### ISSUE TITLE
Error during plugin start: Error loading shared library libtk8.6.so / v2.3.6

### ISSUE THREAD

**Issue by tfohlmeister** [Kannix2005/homeassistant-selve#14]
**Describe the bug**
When starting the plugin (v2.3.6) after the upgrade to HomeAssistant 2023.5.0 i receive the following error:

**Setup failed for custom integration selve: Unable to import component: Error loading shared library libtk8.6.so: No such file or directory (needed by /usr/local/lib/python3.10/lib-dynload/_tkinter.cpython-310-x86_64-linux-gnu.so)** 

**To Reproduce**
1. Install plugin version 2.3.6
2. Try to start plugin

**Expected behavior**
Plugin starts

**Screenshots**
<img width="1548" alt="Screenshot 2023-05-04 at 08 51 45" src="https://user-images.githubusercontent.com/4696987/236131395-797d2b8c-628c-41c6-9269-3017db058035.png">

**Desktop (please complete the following information):**
 - HomeAssistant Version: 2023.5.0
 - OS Hassio
 - Used shutters Commeo

**Additional context**

Logger: homeassistant.setup
Source: setup.py:214
First occurred: 08:28:28 (1 occurrences)
Last logged: 08:28:28

Setup failed for custom integration selve: Unable to import component: Error loading shared library libtk8.6.so: No such file or directory (needed by /usr/local/lib/python3.10/lib-dynload/_tkinter.cpython-310-x86_64-linux-gnu.so)

**Comment by frankfrommelt** [comment]
Same for me.
Is there a way to restore the previous versions of the integration?

**Comment by tfohlmeister** [comment]
You can downgrade to an older version using HACS. I tried it with 2.3.1 but had the same error as above.

**Comment by frankfrommelt** [comment]
Ich habe gerade ein Downgrade meines HA Core auf die Version 2023.4.6 gemacht.
Immer noch die gleiche Fehlermeldung der Selve NG Integration in Version 2.3.6.

**Comment by frankfrommelt** [comment]
he error is caused by a change in "python-selve-new":

the following line has been added:

from tkinter import E

![image](https://user-images.githubusercontent.com/58422143/236225537-ab9c843c-4b11-406d-a006-d690aefba375.png)

**Comment by frankfrommelt** [comment]
it seems that the python-selve-new library did not update to the latest version 2.0.27 on my raspi.
I updated it manually, but the error message is still there.

**Comment by IMMIhomeassistant** [comment]
same here, downgrading selve, wouldnt help me
also homeassistant downgrade wouldnt fix it

found kannix sollution : https://community.home-assistant.io/t/weird-tkinter-error-on-update-of-component/567398
and dit some apt app tk installing, but still no sollution

cant load the integration

**Comment by frankfrommelt** [comment]
Yes, fixed, thank you!

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by IMMIhomeassistant** [comment]
its great, all fixed, i realy like the integration 
thank you verry much
Frank Frommelt wrote:
Yes, fixed, thank you!
Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tfohlmeister** [comment]
Thank you for the fast fix, works great! :-)
