### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by pioga75** [Kannix2005/homeassistant-selve#29]
Hello

I installed the SELVE NG 3.0.14 plug-in via HACS. Selve integration works, but does not find any device/unit. an error appears in LOG HA
![Przechwytywanie](https://github.com/user-attachments/assets/3442fef1-f9b8-4c97-bef1-0b3503df44c9)

**Comment by TwofoldRisk** [comment]
Hi there, do you use and Selve USB RF Gateway Dongle (which is needed for the integration)

If so, did you do a restart of the HA?

Also important you have to connect the selve devices firstly to the dongle via a Selve config programm for windows and then connect the dongle to your ha machine.

Hope that helps.

**Comment by pioga75** [comment]
Thank you for your clarification. Now everything works as it should.

**Comment by pioga75** [comment]
> Hi there, do you use a Selve USB RF Gateway Dongle (which is needed for the integration)
> 
> If so, did you do a restart of the HA?
> 
> Also important you have to connect the selve devices firstly to the dongle via a Selve config programm for windows and then connect the dongle to your ha machine.
> 
> Hope that helps.

Thank you for your clarification. Now everything works as it should.
