### ISSUE TITLE
Home assistants gets really slow

### ISSUE THREAD

**Issue by IMMIhomeassistant** [Kannix2005/homeassistant-selve#3]
**Describe the bug**
homeassistant getting verry slow, also hangs at times

**To Reproduce**
1. reboot
2. in the loggings i find 
3. Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for selve doing blocking calls at custom_components/selve/cover.py, line 88: await selve.discover()
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for selve doing blocking calls at custom_components/selve/cover.py, line 109: await self.selve_device.getDeviceValues()

**Expected behavior**
Using it on selve shutters, total off 6(1 to come) Selve commeo motors
They seems to work normal, but since i put selve rf usb dongle to the system it gets realy slow

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11 (NL) edge browser, but also in the android app
 - Browser = Edge
 - Versie 106.0.1370.52 (Officiële build) (64-bits)

**Smartphone (please complete the following information):**
 - Device: Samsung S21
 - OS: Android12
 - Browser [stock samsung

**Additional context**
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend-versie: 20221010.0 - latest

Also latest version of selve NG

Thanks in advance

**Comment by Kannix2005** [comment]
Hey,

The blocking calls are a known thing, because the gateway itself is rather slow and there has to be a sleep call in the code or some commands do not work. I´m currently rewriting the code a little bit to maybe overcome this issue, though it´s rather hard to fix that, because of the Selve Gateway Firmware which i have no access to.
Regarding the discover function: it is only called at the start of the component. So this should only happen at boot or on component load.

I can not really tell, that the component slows anything down on my side. Can you please tell me on which system you installed HA? And which other components you are using?

Best
Stefan

**Comment by IMMIhomeassistant** [comment]
Hi stefan,

At firts thankyou for youre work, appreciate it 100%

The hardware is for now an raspberry pi4 (4GB), and a 256gb ssd via usb 3
the dwains dashboard takes about 3-5 secs to reload

my programs are basics, some zigbee, wifi and hue lamps.
esp home (light use), node red (installed, not used yet)
some light routines, but noting spectaculair
and the selve commeo motors 6X shutters (1 to come)
uninstalled selve NG (sorry ;) ) and verry noticable speed increasement

Herman

⁣BlueMail voor Android downloaden ​

Op 26 okt. 2022 23:19, om 23:19, Stefan Altheimer ***@***.***> schreef:
>Hey,
>
>The blocking calls are a known thing, because the gateway itself is
>rather slow and there has to be a sleep call in the code or some
>commands do not work. I´m currently rewriting the code a little bit to
>maybe overcome this issue, though it´s rather hard to fix that, because
>of the Selve Gateway Firmware which i have no access to.
>Regarding the discover function: it is only called at the start of the
>component. So this should only happen at boot or on component load.
>
>I can not really tell, that the component slows anything down on my
>side. Can you please tell me on which system you installed HA? And
>which other components you are using?
>
>Best
>Stefan
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Kannix2005/homeassistant-selve/issues/3#issuecomment-1292663916
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by Kannix2005** [comment]
Then you have to wait for the new version. Theres a speed bump in there ;)

Best Stefan

**Comment by IMMIhomeassistant** [comment]
Hi Stefan,

that was a verry quick release, it is kind of working now (not that much lagg any more)
major thanks!!!!

installed the speedbump, and its an improvement, on the line 88, custom_components/selve/cover.py
i've only left some line 109 custom_components/selve/cover.py

Logger: homeassistant.util.async_
Source: util/async_.py:180
First occurred: 20:15:47 (18 occurrences)
Last logged: 20:16:19

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for selve doing blocking calls at custom_components/selve/cover.py, line 109: await self.selve_device.getDeviceValues()

**Comment by Kannix2005** [comment]
This version is currently in Alpha. I have to do some work on it and nothing is tested. Therefore there is still a legacy version available. Which one are you using?

**Comment by IMMIhomeassistant** [comment]
currently im using the 1.0.2 version, gives some errors now and then, but the major lagg is less

**Comment by Kannix2005** [comment]
Then i´ll close the issue as it seems to be resolved. Maybe try out the new version.

**Comment by IMMIhomeassistant** [comment]
i wanna thank you for the great effort kannix
i installed the new version 2.2.6 , all the problems solved
