### ISSUE TITLE
Funktion öffnet ausgegraut 

### ISSUE THREAD

**Issue by Julger92** [Kannix2005/homeassistant-selve#4]
Hallo, 

nach dem letzten Update funktioniert die Funktion Rollladen öffnen nicht mehr.

**Comment by Kannix2005** [comment]
Hey,
Hast du ein Log für mich? Und welches Funkprotokoll nutzt du? Iveo oder Commeo?

LG

**Comment by Julger92** [comment]
Hey! Ich denke das Protokoll wird leer sein, da lediglich der öffnen Button ausgegraut ist.Ich nutze Iveo.GrüßeJulian Von meinem iPhone gesendetAm 05.11.2022 um 22:19 schrieb Stefan Altheimer ***@***.***>:﻿
Hey,
Hast du ein Log für mich? Und welches Funkprotokoll nutzt du? Iveo oder Commeo?
LG

**Comment by Kannix2005** [comment]
Ohne das HA Log zu haben, kann ich leider nicht viel tun. Bei mir funktioniert alles.
