### ISSUE TITLE
Log Entry: Configured port not valid!

### ISSUE THREAD

**Issue by Deinjo** [Kannix2005/homeassistant-selve#9]
I am using version v2.2.17 and I am using the Selve USB stick at /dev/ttyUSB0.
The control of the cover is possible without problems so far.

Today I discovered that I have the following error message in the HA logs:

**This error originated from a custom integration.
Logger: custom_components.selve.cover
Source: custom_components/selve/cover.py:82
Integration: Selve NG (documentation, issues)
First occurred: 00:53:34 (1 occurrences)
Last logged: 00:53:34
Configured port not valid!**

![grafik](https://user-images.githubusercontent.com/48606253/210286386-c331919b-18a8-4c02-b011-2748313f84c3.png)

**information:**
- Home Assistant 2022.9.7 
- Supervisor 2022.12.1 
- Frontend 20220907.2
- Raspberry4
- 6 Selve iveo cover

**Comment by Kannix2005** [comment]
Fixed with v2.2.22
